### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by russelljjarvis**
So the files I would propose trying to merge, include adding exhaustive search in as discussed in the email.

Also there needs to be some changes to neuronunit/neuronunit/tests/__init__.py Rheobase, that facilitate the option of retaininig a Rheobase test, but performing the rheobase search implementation elsewhere.

Some class constructor signatures have the keyword argument backend set to none now also as below which is located here in [code](https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/models/reduced.py#L18-L23).

```
    def __init__(self, LEMS_file_path, name=None, backend=None, attrs={}):
        """
        LEMS_file_path: Path to LEMS file (an xml file).
        name: Optional model name.
        """
        super(ReducedModel,self).__init__(LEMS_file_path,name=name,backend=backend,attrs=attrs)
```

### CODE REVIEW

**Comment by russelljjarvis** [comment]
I am just redoing this pull request, as I have much improved nsga.py and exhaustive_search.py

nsga now optimizes all or most of the Izhikevitch parameters, and it is fast, it may not be the most readable code, but I am making progress on that issue too, the file is much more documented now.

Both files work on my local machine, they are failing in the travis build, but this has something to do with docker and its pulling from ubuntu/debian repositories, not anything to do with python code, yet.

Some of the same issues, still apply for the above pull request.

I forgot to say also in the previous pull request. The file 'get_neab.py' (get neuroelectro, and allan brain data) is an important part of my approach, I just separated out the task of downloading all of that data from the optimization code, since the getting of data is separate to the task of optimizing the data, and I wanted to separate them out to reduce visual clutter. 

This might or might not be good for jupyter notebooks, depending on whether or not the task of the notebook is to show the user how to get access to data as well as how to optimize it.

Its a bummer that scoop can only work on pickable objects, because it forces the user of DEAP to not be able to hide implementation complexity inside objects (thats one reason why the nsga.py file is so big and complex, also it is more complex than it needs to be, I can put a lot of repetitive code in a function definition, I just need more time to figure out how to make that work.

**Comment by rgerkin** [comment]
@russelljjarvis Can you provide a set of tests, whether in notebooks or otherwise, that you expect this pull request to pass?  When I merge and make any changes of my own (to fix my tests), I want to make sure that it still passes those tests.  Also let me know which environment they are currently passing in for you, e.g. a specific Docker container, your laptop, etc.

**Comment by russelljjarvis** [comment]
The build env is based on the dockerfile here and built on my laptop:
https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/tests/Dockerfile

It was premature to say that it worked, or it did work, until I exposed the search to all of the parameters.

Is it okay if I provide the tests that it passes over the next few weeks. I have a lot on.

**Comment by rgerkin** [comment]
My vision is to have the more illustrative tests (the kind that show a person how to use NeuronUnit) in notebooks, which get run directly (through [this](https://github.com/russelljjarvis/neuronunit/blob/dev/test_all.py), and then some of the more boring tests are run in the usual way.  

It would be really great though if you can just provide one script for now that runs in the Docker build and does something you think represents the essence of your recent work.  It is even OK if it chokes somewhere in the middle of the optimization, as long as enters it and runs a few iterations.  I just want to have something to work with as I begin to merge the commits.

**Comment by russelljjarvis** [comment]
The test_all.py looks great. I will def use that to inform my tests.

To add to the showcase:

The files that are run in my docker [image](https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/tests/Dockerfile):

Is good. It does not choke if I run it on only limited parameters rather than all the Izehikitch parameters.

```
ENTRYPOINT python -m scoop nsga.py && python -m scoop exhaustive_search.py
```

I did try to build the whole docker image from scratch again, in order to expose any errors that you might be seeing, and unfortunately I did find a build error.

I think the error comes from more changes to the Allen Brain API as aibs.py fails again.
See below:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: '354190013_rheobase'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 298, in <module>
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 92, in main
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 252, in run
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 213, in setupEnvironment
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/bootstrap/__main__.py", line 35, in <lambda>
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "exhaustive_search.py", line 19, in <module>
    import get_neab
  File "/home/jovyan/neuronunit/neuronunit/tests/get_neab.py", line 31, in <module>
    observation = aibs.get_observation(dataset_id,'rheobase')
  File "/home/jovyan/neuronunit/neuronunit/tests/../../neuronunit/aibs.py", line 27, in get_observation
    value = db[identifier]
  File "/opt/conda/lib/python3.5/shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
EOFError: Ran out of input
[2017-02-28 23:09:08,293] launcher  (127.0.0.1:45736) INFO    Root process is done.
[2017-02-28 23:09:08,339] launcher  (127.0.0.1:45736) INFO    Finished cleaning spawned subprocesses.
```

**Comment by russelljjarvis** [comment]
>My vision is to have the more illustrative tests (the kind that show a person how to use NeuronUnit) in notebooks, which get run directly (through this, and then some of the more boring tests are run in the usual way.

Regarding the test class

I was thinking it should do several obvious things first.

It should check that `dt` and time vectors recorded and output by ```model.inject_square_current```, have the expected values.

It should check return types for std and median are useable for extreme edge case parameter values.
```
model.inject_square_current(self.params['injected_square_current'])
median = model.get_median_vm() # Use median for robustness.
std = model.get_std_vm()
spkc=model.get_spike_count()
model.get_membrane_potential()   
```

Finally it should run `exhaustive_search` and `nsga` and use the output of exhaustive_search as a ground truth for comparison to the output of nsga. On this last issue, I have noticed that travis jobs have time limits after which, if your job exceeds the limit its artificially shutdown. 

I wonder if you think its viable to run scoop inside the test class? I was thinking of saving travis's time by 
making a list of python scripts to execute in parallel using scoop.futures.map

```
import unittest
import sys
import os
import warnings
from scoop import futures
import os


def testfunc2map(file2map):
    exec_string='python '+str(file2map)
    os.system(exec_string)
    return 0

class OptimizationTestCase(unittest.TestCase):	
    def testrun_all_files():
        '''
        run all files as different CPU threads, thus saving time on travis
        Since scoop is designed to facilitate nested forking/parallel job dispatch
        This approach should be scalable to larger CPU pools.
        '''
        files_to_exec=['exhaustive_search.py','nsga.py']
        clean_or_dirty=list(futures.map(testfunc2map,files_to_exec))   
        return clean_or_dirty

if __name__ == '__main__':
    unittest.main()
```

One problem with this approach is that I need to use two -m arguments then and I don't know the required syntax.
```
python -m scoop -m unittest test_all
```

Anyway, I am sure someone has figured out how to do embarrassingly parallel execution of unittests on files. I will search around to see what exists.

**Pull request merged**
